name: test_test
on: 
  push

jobs:
  qqqqqq:
    runs-on: ubuntu-latest
    steps:
      - name: Step that should fails
        run: exit 1
        continue-on-error: true

      - name: Step after failure
        run: echo "Этот шаг выполнится несмотря на ошибку выше"
