name: HOOPS main

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Generate test artifact
        run: |
          mkdir artifacts
          for i in $(seq 1 9); do
            openssl rand -out artifacts/artifact_$i.txt 2018741824
          done

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test-${{ github.run_id }}
          name: "Automated test release"
          files: artifacts/*
