on:
  push

jobs:
  include-example:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        city: [moscow, saint_petersburg]
        transport: [bus, train]
        include:
          - weather: sunny
          - weather: rainy
            transport: bus
          - city: moscow
            population: large
          - city: yekaterinburg
            transport: train
    steps:
      - name: qqqq
        run: echo "asd"
